name: Build Terminal Tabs
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install vcpkg
        shell: cmd
        run: |
          if not exist dep\vcpkg (
            git clone https://github.com/Microsoft/vcpkg.git dep\vcpkg
          )
          cd dep\vcpkg
          .\bootstrap-vcpkg.bat
          cd ..\..

      - name: Restore packages by nuget
        shell: cmd
        run: |
          nuget restore dep\nuget\packages.config -ConfigFile NuGet.Config -PackagesDirectory packages
          nuget restore build\packages.config -ConfigFile NuGet.Config -PackagesDirectory packages
          nuget restore tools\packages.config -ConfigFile NuGet.Config -PackagesDirectory packages
          nuget restore .nuget\packages.config -ConfigFile NuGet.Config -PackagesDirectory packages
          nuget restore scratch\ScratchIslandApp\WindowExe\packages.config -ConfigFile NuGet.Config -PackagesDirectory packages

      - name: Build TerminalAppLib
        shell: cmd
        run: |
          set SolutionDir=%CD%\
          echo %SolutionDir%
          set VCPKG_ROOT=%CD%\dep\vcpkg
          mkdir src\packages
          xcopy /E /I /Y packages\ src\packages\
          for /f "delims=" %%i in ('dir "%ProgramFiles%\Microsoft SDKs\Windows\v10.*" /b /ad /on 2^>nul ^| tail -1') do set "SDKVER=%%i"
          echo Using SDK: %SDKVER%
          set WindowsSdkDir=%ProgramFiles%\Microsoft SDKs\Windows\%SDKVER%
          set WindowsSDKVersion=%SDKVER%
          set WindowsTargetPlatformVersion=%SDKVER%
          msbuild src\cascadia\TerminalApp\TerminalAppLib.vcxproj ^
            /p:SolutionDir=%SolutionDir% ^
            /p:WindowsSdkDir="%WindowsSdkDir%" ^
            /p:WindowsSDKVersion=%SDKVER% ^
            /p:WindowsTargetPlatformVersion=%SDKVER% ^
            /p:Configuration=Release ^
            /p:Platform=x64 ^
            /t:Restore,Build
          
      - name: Upload tabs DLL
        uses: actions/upload-artifact@v4
        with:
          name: TerminalAppLib-SquareTabs
          path: bin\**\TerminalApp.dll
